@echo off
echo Setting up Vercel environment variables...

echo Adding NEXT_PUBLIC_SUPABASE_URL...
echo https://pamzfhiiuvmtlwwvufut.supabase.co | vercel env add NEXT_PUBLIC_SUPABASE_URL production

echo Adding NEXT_PUBLIC_SUPABASE_ANON_KEY...
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbXpmaGlpdXZtdGx3d3Z1ZnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTgwNzYsImV4cCI6MjA2OTM5NDA3Nn0.nK7BnVHNwoHuVCnkp2oWgGfyDxCA_Tjfc_0uhuKTF74 | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production

echo Adding NEXTAUTH_SECRET...
echo cabo-fit-pass-secret-key-2024 | vercel env add NEXTAUTH_SECRET production

echo Done setting up environment variables!
echo Now running deployment...
vercel --prod --yes